# Generated by Django 4.0.5 on 2022-09-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
