# Generated by Django 4.0.5 on 2022-09-17 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_delete_admin_book_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover_image',
        ),
    ]
